---
- name: DBserver setup
  hosts: dbservers
  become: yes
  vars:
    #dbname: electric
    #dbuser: current
    #dbpass: tesla

  tasks:
    - debug:
        msg: "the db name is {{dbname}}"
    - debug:
        var: dbuser

    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Install python-mysql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present


    - name: Start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'accounts'
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
     
    - name: Create database user with name 'vprofile'
      community.mysql.mysql_db:
        name: "{{dbuser}}"
        login_password: "{{dbpass}}"
          #priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

      register: dbout #json output
    - name: print dbout variable
      debug:
        var: dbout
