---

- name: provisioning servers
  hosts: all
  become: yes
  tasks:
    - name: install ntp agent on centos
      yum:
        name: chrony
        state: present
      when: ansible_distribution == "CentOS"

    - name: install ntp on ubuntu
      apt:
        name: ntp
        state: present
        update_cache: yes #run update first 
      when: ansible_distribution == "Ubuntu"

    - name: start service
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"
