---

- name: Print facts
  hosts: all
  #gather_facts: False
  tasks:
    - name: print os name
      debug:
        var: ansible_distribution

    - name: print free memory
      debug:
        var: ansible_memory_mb.real.free
