---

- name: Understanding vars
  hosts: all
  become: yes
  vars:
    #USRNM: playuser
    #COMM: variable ifrom playbook
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: usrout
    - debug:
        var: usrout.name
    - debug:
        var: usrout.comment
